name: Greet on new issue and pull request

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello user.  You just created an issue.  I'm executed by GitHub actions."
        pr-message: "Message that will be displayed on users' first pull request"
